// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.API.Infrastructure.Data;

#nullable disable

namespace Nexus.API.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204110255_AddDiagram")]
    partial class AddDiagram
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeSnippetTags", b =>
                {
                    b.Property<Guid>("CodeSnippetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("CodeSnippetId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CodeSnippetTags", "dbo");
                });

            modelBuilder.Entity("DocumentTags", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.CodeSnippetAggregate.CodeSnippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OriginalSnippetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CodeSnippets_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_CodeSnippets_CreatedBy");

                    b.HasIndex("OriginalSnippetId")
                        .HasDatabaseName("IX_CodeSnippets_OriginalSnippetId")
                        .HasFilter("[OriginalSnippetId] IS NOT NULL");

                    b.ToTable("CodeSnippets", "dbo");
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.Diagram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DiagramId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagramType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Diagrams_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Diagrams_CreatedBy");

                    b.HasIndex("DiagramType")
                        .HasDatabaseName("IX_Diagrams_DiagramType")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Diagrams_IsDeleted");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Diagrams_UpdatedAt");

                    b.ToTable("Diagrams", "dbo");
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.DiagramConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConnectionId");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int");

                    b.Property<string>("ControlPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SourceElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetElementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId")
                        .HasDatabaseName("IX_DiagramConnections_DiagramId");

                    b.HasIndex("SourceElementId")
                        .HasDatabaseName("IX_DiagramConnections_SourceElement");

                    b.HasIndex("TargetElementId")
                        .HasDatabaseName("IX_DiagramConnections_TargetElement");

                    b.ToTable("DiagramConnections", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_DiagramConnections_Elements", "[SourceElementId] <> [TargetElementId]");

                            t.HasCheckConstraint("CK_DiagramConnections_Type", "[ConnectionType] BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.DiagramElement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ElementId");

                    b.Property<string>("CustomProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShapeType")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ZIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DiagramId")
                        .HasDatabaseName("IX_DiagramElements_DiagramId");

                    b.HasIndex("LayerId")
                        .HasDatabaseName("IX_DiagramElements_LayerId");

                    b.HasIndex("DiagramId", "ZIndex")
                        .HasDatabaseName("IX_DiagramElements_DiagramId_ZIndex");

                    b.ToTable("DiagramElements", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_DiagramElements_Opacity", "[Opacity] >= 0 AND [Opacity] <= 1");

                            t.HasCheckConstraint("CK_DiagramElements_Rotation", "[Rotation] >= 0 AND [Rotation] < 360");

                            t.HasCheckConstraint("CK_DiagramElements_ShapeType", "[ShapeType] BETWEEN 0 AND 99");

                            t.HasCheckConstraint("CK_DiagramElements_Size", "[Width] > 0 AND [Height] > 0");
                        });
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LayerId");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId")
                        .HasDatabaseName("IX_DiagramLayers_DiagramId");

                    b.HasIndex("DiagramId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_DiagramLayers_DiagramId_Order");

                    b.ToTable("DiagramLayers", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_DiagramLayers_Order", "[Order] >= 0");
                        });
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DocumentAggregate.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("LastEditedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReadingTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Documents_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Documents_CreatedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Documents_Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Documents_UpdatedAt");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DocumentAggregate.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_DocumentVersions_CreatedAt");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_DocumentVersions_DocumentVersion");

                    b.ToTable("DocumentVersions", (string)null);
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DocumentAggregate.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tags_Name");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Nexus.API.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidatedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("JwtId")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_JwtId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("UserId", "Used", "Invalidated", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserValidation");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("CodeSnippetTags", b =>
                {
                    b.HasOne("Nexus.API.Core.Aggregates.CodeSnippetAggregate.CodeSnippet", null)
                        .WithMany()
                        .HasForeignKey("CodeSnippetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Core.Aggregates.DocumentAggregate.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocumentTags", b =>
                {
                    b.HasOne("Nexus.API.Core.Aggregates.DocumentAggregate.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Core.Aggregates.DocumentAggregate.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.CodeSnippetAggregate.CodeSnippet", b =>
                {
                    b.OwnsOne("Nexus.API.Core.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("CodeSnippetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("CodeSnippetId");

                            b1.ToTable("CodeSnippets", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("CodeSnippetId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.ProgrammingLanguage", "Language", b1 =>
                        {
                            b1.Property<Guid>("CodeSnippetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FileExtension")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("FileExtension");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LanguageName");

                            b1.Property<string>("Version")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("LanguageVersion");

                            b1.HasKey("CodeSnippetId");

                            b1.ToTable("CodeSnippets", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("CodeSnippetId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.SnippetMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("CodeSnippetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CharacterCount")
                                .HasColumnType("int")
                                .HasColumnName("CharacterCount");

                            b1.Property<int>("ForkCount")
                                .HasColumnType("int")
                                .HasColumnName("ForkCount");

                            b1.Property<bool>("IsPublic")
                                .HasColumnType("bit")
                                .HasColumnName("IsPublic");

                            b1.Property<int>("LineCount")
                                .HasColumnType("int")
                                .HasColumnName("LineCount");

                            b1.Property<int>("ViewCount")
                                .HasColumnType("int")
                                .HasColumnName("ViewCount");

                            b1.HasKey("CodeSnippetId");

                            b1.HasIndex("IsPublic")
                                .HasDatabaseName("IX_CodeSnippets_PublicDeleted");

                            b1.ToTable("CodeSnippets", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("CodeSnippetId");
                        });

                    b.OwnsMany("Nexus.API.Core.Aggregates.CodeSnippetAggregate.SnippetFork", "Forks", b1 =>
                        {
                            b1.Property<Guid>("OriginalSnippetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ForkedSnippetId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("ForkedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("ForkedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("OriginalSnippetId", "ForkedSnippetId");

                            b1.ToTable("SnippetForks", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("OriginalSnippetId");
                        });

                    b.Navigation("Forks");

                    b.Navigation("Language")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.Diagram", b =>
                {
                    b.OwnsOne("Nexus.API.Core.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("DiagramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("DiagramId");

                            b1.ToTable("Diagrams", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DiagramId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.DiagramCanvas", "Canvas", b1 =>
                        {
                            b1.Property<Guid>("DiagramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BackgroundColor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("BackgroundColor");

                            b1.Property<int?>("GridSize")
                                .HasColumnType("int")
                                .HasColumnName("GridSize");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CanvasHeight");

                            b1.Property<decimal>("Width")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CanvasWidth");

                            b1.HasKey("DiagramId");

                            b1.ToTable("Diagrams", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DiagramId");
                        });

                    b.Navigation("Canvas")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.DiagramConnection", b =>
                {
                    b.HasOne("Nexus.API.Core.Aggregates.DiagramAggregate.Diagram", null)
                        .WithMany("_connections")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nexus.API.Core.ValueObjects.ConnectionStyle", "Style", b1 =>
                        {
                            b1.Property<Guid>("DiagramConnectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("StrokeColor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("StrokeColor");

                            b1.Property<string>("StrokeDashArray")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("StrokeDashArray");

                            b1.Property<int>("StrokeWidth")
                                .HasColumnType("int")
                                .HasColumnName("StrokeWidth");

                            b1.HasKey("DiagramConnectionId");

                            b1.ToTable("DiagramConnections", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DiagramConnectionId");
                        });

                    b.Navigation("Style")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.DiagramElement", b =>
                {
                    b.HasOne("Nexus.API.Core.Aggregates.DiagramAggregate.Diagram", null)
                        .WithMany("_elements")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nexus.API.Core.ValueObjects.ElementStyle", "Style", b1 =>
                        {
                            b1.Property<Guid>("DiagramElementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FillColor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("FillColor");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FontFamily");

                            b1.Property<int>("FontSize")
                                .HasColumnType("int")
                                .HasColumnName("FontSize");

                            b1.Property<decimal>("Opacity")
                                .HasColumnType("decimal(3,2)")
                                .HasColumnName("Opacity");

                            b1.Property<decimal>("Rotation")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("Rotation");

                            b1.Property<string>("StrokeColor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("StrokeColor");

                            b1.Property<int>("StrokeWidth")
                                .HasColumnType("int")
                                .HasColumnName("StrokeWidth");

                            b1.HasKey("DiagramElementId");

                            b1.ToTable("DiagramElements", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DiagramElementId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.Point", "Position", b1 =>
                        {
                            b1.Property<Guid>("DiagramElementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("X")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PositionX");

                            b1.Property<decimal>("Y")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PositionY");

                            b1.HasKey("DiagramElementId");

                            b1.ToTable("DiagramElements", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DiagramElementId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.Size", "Size", b1 =>
                        {
                            b1.Property<Guid>("DiagramElementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Height");

                            b1.Property<decimal>("Width")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Width");

                            b1.HasKey("DiagramElementId");

                            b1.ToTable("DiagramElements", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DiagramElementId");
                        });

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();

                    b.Navigation("Style")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.Layer", b =>
                {
                    b.HasOne("Nexus.API.Core.Aggregates.DiagramAggregate.Diagram", null)
                        .WithMany("_layers")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DocumentAggregate.Document", b =>
                {
                    b.OwnsOne("Nexus.API.Core.ValueObjects.DocumentContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PlainText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContentPlainText");

                            b1.Property<string>("RichText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContentRichText");

                            b1.Property<int>("WordCount")
                                .HasColumnType("int")
                                .HasColumnName("WordCount");

                            b1.HasKey("DocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("DocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DocumentAggregate.DocumentVersion", b =>
                {
                    b.HasOne("Nexus.API.Core.Aggregates.DocumentAggregate.Document", null)
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nexus.API.Core.ValueObjects.DocumentContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("DocumentVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PlainText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContentPlainText");

                            b1.Property<string>("RichText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContentRichText");

                            b1.Property<int>("WordCount")
                                .HasColumnType("int")
                                .HasColumnName("WordCount");

                            b1.HasKey("DocumentVersionId");

                            b1.ToTable("DocumentVersions");

                            b1.WithOwner()
                                .HasForeignKey("DocumentVersionId");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsOne("Nexus.API.Core.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("IX_Users_Email");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.PersonName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("EmailDigest")
                                .HasColumnType("int")
                                .HasColumnName("EmailDigest");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Language");

                            b1.Property<bool>("NotificationsEnabled")
                                .HasColumnType("bit")
                                .HasColumnName("NotificationsEnabled");

                            b1.Property<int>("Theme")
                                .HasColumnType("int")
                                .HasColumnName("Theme");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Nexus.API.Core.ValueObjects.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AvatarUrl")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AvatarUrl");

                            b1.Property<string>("Bio")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("Bio");

                            b1.Property<string>("Department")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Department");

                            b1.Property<string>("Title")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DiagramAggregate.Diagram", b =>
                {
                    b.Navigation("_connections");

                    b.Navigation("_elements");

                    b.Navigation("_layers");
                });

            modelBuilder.Entity("Nexus.API.Core.Aggregates.DocumentAggregate.Document", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
